alias ll='ls -alF'
alias la='ls -A'
alias lla='ls -al'
alias sl='ls'
#alias l='ls -CF'
alias py='python3'
alias gp='grep'
alias ..='cd ..'
alias ...='cd ../..'
alias md='mkdir'
alias rd='rmdir'
alias shsy='ssh kevin.rose2@syccuxas01.pcc.edu'
alias stsy='sftp kevin.rose2@syccuxas01.pcc.edu'

